name: go-goldilocks pipeline
on: [push]

jobs:
  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest, raspbian-latest, macos-11.0 ]
    runs-on: ${{ matrix.platform }}
    steps:
        - name: Setup
          uses: actions/setup-go@v1
          with:
            go-version: 1.14.x
          id: go
        - name: Checkout
          uses: actions/checkout@v1
        - name: Version
          if: ${{ matrix.platform == 'macos-latest' }}
          run: system_profiler SPSoftwareDataType
        - name: Test
          run: |
           go test -v
  tag:
    needs: [test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Bump version
        uses: anothrNick/github-tag-action@1.13.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: "patch"
          RELEASE_BRANCHES: "master"
          WITH_V: true
