name: go-goldilocks pipeline
on: [push]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, raspbian-private, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
        - name: Setup
          uses: actions/setup-go@v1
          with:
            go-version: 1.21.x
          id: go
        - name: Checkout
          uses: actions/checkout@v1
        - name: Test
          run: go test -v
  tag:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Bump version
        id: version_bump
        uses: anothrNick/github-tag-action@1.38.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: "patch"
          RELEASE_BRANCHES: "master"
          WITH_V: true
      - name: Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{steps.version_bump.outputs.tag}}
          release_name: go-goldilocks ${{steps.version_bump.outputs.tag}}
          draft: false
          prerelease: false
