name: Build

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
        - name: Setup
          uses: actions/setup-go@v1
          with:
            go-version: 1.14.x
          id: go
        - name: Checkout
          uses: actions/checkout@v1
        - name: Test
          run: go test ./...